version: '3.9'

services: 
    postgres:
        image: postgres
        ports: 
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=payments
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
    mongo:
        image: mongo:latest
        environment: 
            MONGO_USERNAME: root
            MONGO_PASSWORD: rootpassword
        ports: 
            - 27017:27017
        volumes: 
            - mongodb:/data/db
volumes: 
    mongodb: