version: '3.7'
services: 
    mongodb:
        image: mongo:latest
        environment: 
            MONGO_USERNAME: root
            MONGO_PASSWORD: rootpassword
        ports: 
            - 27017:27017
        volumes: 
            - mongodb:/data/db
        
volumes: 
    mongodb: